### PR TITLE
Port DeformConv to use the Dispatcher and support Autocast

### LINKED ISSUE #2833: fp16 for deform_conv2d missing?
## To Reproduce
This example below is copy pasted from https://pytorch.org/docs/stable/torchvision/ops.html
except dtypes are added.
The first part with float32 runs fine, but the second part with float16
produces error:

>  File "/home/hu-mka/venvs/pytorch/lib/python3.8/site-packages/torchvision/ops/deform_conv.py", line 67, in deform_conv2d
>     return torch.ops.torchvision.deform_conv2d(
> RuntimeError: _th_addmm_ not supported on CPUType for Half

Terveisin, Markus

```
input = torch.rand(5, 3, 10, 10, dtype=torch.float32)
kh, kw = 3, 3
weight = torch.rand(5, 3, kh, kw, dtype=torch.float32)
offset = torch.rand(5, 2 * kh * kw, 8, 8, dtype=torch.float32)
out = ops.deform_conv2d(input, offset, weight)
print(out)
input = torch.rand(5, 3, 10, 10, dtype=torch.float16)
kh, kw = 3, 3
weight = torch.rand(5, 3, kh, kw, dtype=torch.float16)
offset = torch.rand(5, 2 * kh * kw, 8, 8, dtype=torch.float16)
out = ops.deform_conv2d(input, offset, weight)
print(out)
```

## Environment

(pytorch) hu-mka@humkaLenovo:~/Downloads$ python collect_env.py 
Collecting environment information...
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-3ubuntu2) 8.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.105
GPU models and configuration: GPU 0: GeForce GTX 1650 with Max-Q Design
Nvidia driver version: 450.80.02
cuDNN version: Probably one of the following:
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.0
[pip3] pytorch-lightning==0.9.0
[pip3] torch==1.6.0
[pip3] torchfunc==0.2.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.7.0
[pip3] torchviz==0.0.1
[conda] numpy                     1.19.1                   pypi_0    pypi

### PR DESCRIPTION
**Pull request by datumbox**
Fixes #2833 

part of #2797 and #2796

### CODE REVIEW

File: torchvision/csrc/DeformConv.h [hunk 1]
```diff
@@ -1,89 +1,105 @@
...
+
+std::tuple<at::Tensor, at::Tensor, at::Tensor, at::Tensor>
+_deform_conv2d_backward(
+    const at::Tensor& grad,
+    const at::Tensor& input,
+    const at::Tensor& weight,
+    const at::Tensor& offset,
+    const at::Tensor& bias,
+    const int64_t stride_h,
+    const int64_t stride_w,
```
Comment (fmassa) [inline torchvision/csrc/DeformConv.h:80]: high-level question: Can't we use `std::pair` here?
If not, I think the idiom in PyTorch is to use [`IntArrayRef &` or something like that ](https://github.com/pytorch/pytorch/blob/8640905088a002dbf149b59333a190c8aed2f5e5/aten/src/ATen/native/AveragePool2d.cpp#L341-L343)

Comment (fmassa) [reply torchvision/csrc/DeformConv.h:80]: For information we can keep this as is (as the original registered op was already splitting it up in individual args)

File: torchvision/csrc/DeformConv.h [hunk 2]
```diff
@@ -1,89 +1,105 @@
...
+    const int64_t pad_h,
```
Comment (fmassa) [inline torchvision/csrc/DeformConv.h:81]: having `const` and a elementary type is a bit of an anti-pattern I think, as you pass the argument by value anyway so you can't modify it.

Comment (datumbox) [reply torchvision/csrc/DeformConv.h:81]: Agree it's an anti-pattern. I'm trying to make the dispatcher work with the minimal changes to the previous code. Once it does I'll clean it up.

File: torchvision/csrc/DeformConv.h [hunk 3]
```diff
@@ -1,89 +1,105 @@
...
+    const int64_t groups,
+    const int64_t offset_groups) {
+  static auto op = c10::Dispatcher::singleton()
+                       .findSchemaOrThrow("torchvision::deform_conv2d", "")
+                       .typed<decltype(deform_conv2d)>();
+  return op.call(
       input.contiguous(),
       weight.contiguous(),
       offset.contiguous(),
       bias.contiguous(),
```
Comment (fmassa) [inline torchvision/csrc/DeformConv.h:29]: I think this is a potential bug in here for non-contiguous tensors, see https://github.com/pytorch/vision/pull/2384/commits/1175bbc3b47e5bf50da4ce0309756c7edf46c9e0 for what we had to do for NMS.
From my understanding, we should avoid adding code (like checks) in the dispatcher code, as it might never be called (and thus the `contiguous()` calls might not be invoked).
Can you instead move those `contiguous` calls inside the C++ / CUDA operators?

File: torchvision/csrc/DeformConv.h [hunk 4]
```diff
@@ -1,89 +1,105 @@
...
+  static auto op =
+      c10::Dispatcher::singleton()
+          .findSchemaOrThrow("torchvision::_deform_conv2d_backward", "")
+          .typed<decltype(_deform_conv2d_backward)>();
+  return op.call(
       grad.contiguous(),
       input.contiguous(),
       weight.contiguous(),
       offset.contiguous(),
       bias.contiguous(),
```
Comment (fmassa) [inline torchvision/csrc/DeformConv.h:96]: Same comment here, I'm afraid that we might need to move those `contiguous` calls to the respective functions in C++ / CUDA.

cc @ezyang can you confirm?

**Review by fmassa — COMMENTED** [review]
PR looks great, thanks a lot @datumbox !

I have one comment that I think might be a bug, but I'll let @ezyang confirm.

File: torchvision/csrc/DeformConv.h (hunk 4 above)
Comment (datumbox) [reply torchvision/csrc/DeformConv.h]: I discussed, I'm patching this to unblock the merge and if @ezyang thinks it was not a problem I'll send another PR to revert.

File: torchvision/csrc/DeformConv.h [hunk 5]
```diff
@@ -105,14 +121,18 @@ class DeformConv2dFunction
       int64_t dilation_w,
       int64_t groups,
       int64_t offset_groups) {
-    auto output = DeformConv2d_forward(
+    at::AutoNonVariableTypeMode g; // TODO_vv: check if necessary
```
Comment (fmassa) [inline torchvision/csrc/DeformConv.h:124]: This is present in RoIAlign, so I think I'd keep it.

Even though it appears that `g` this is not being used, it's a [RAII class](https://en.cppreference.com/w/cpp/language/raii)

File: torchvision/csrc/DeformConv.h [hunk 6]
```diff
@@ -207,6 +285,37 @@ at::Tensor deform_conv2d(
...
+      stride_h,
+      stride_w,
+      pad_h,
+      pad_w,
+      dilation_h,
+      dilation_w,
+      groups,
+      offset_groups);
+  return std::make_tuple(result[0], result[1], result[2], result[3]);
+}
```
Comment (fmassa) [inline torchvision/csrc/DeformConv.h:321]: nit for a follow-up cleanup: newline

File: torchvision/csrc/cpu/DeformConv_cpu.cpp [hunk 7]
```diff
@@ -232,22 +232,23 @@ at::Tensor DeformConv2d_forward_cpu(
...
+    const at::Tensor& bias_param,
+    int64_t stride_h,
+    int64_t stride_w,
+    int64_t pad_h,
+    int64_t pad_w,
+    int64_t dil_h,
+    int64_t dil_w,
+    int64_t n_weight_grps,
+    int64_t n_offset_grps) {
+  at::Tensor&& input = input_param.contiguous();
```
Comment (fmassa) [inline torchvision/csrc/cpu/DeformConv_cpu.cpp:244]: This is not something that I generally see being done within the PyTorch codebase.

For example I'd generally see [this in PyTorch](https://github.com/pytorch/pytorch/blob/daf2a6a29da5109157bb44fc5e4dbc4fb5c56c15/aten/src/ATen/native/ConvolutionMM2d.cpp#L128)

**Review by fmassa — APPROVED** [review]
PR is good to merge, thanks!

I have one question regarding `Tensor&&`, which I'm not used to seeing in the PyTorch codebase.

We can merge the PR as is now, but I would maybe we should check on this afterwards

File: torchvision/csrc/cpu/DeformConv_cpu.cpp [hunk 8]
```diff
@@ -917,16 +897,25 @@ static at::Tensor deform_conv2d_backward_parameters_cpu(
...
+    const at::Tensor& bias_param,
+    int64_t stride_h,
+    int64_t stride_w,
+    int64_t pad_h,
+    int64_t pad_w,
+    int64_t dil_h,
+    int64_t dil_w,
+    int64_t n_weight_grps,
+    int64_t n_offset_grps) {
+  at::Tensor&& grad_out = grad_out_param.contiguous();
```
Comment (ezyang) [inline torchvision/csrc/cpu/DeformConv_cpu.cpp:913]: Not sure why you're using a universal reference here...

File: torchvision/csrc/DeformConv.h (hunk 6 above)
Comment (datumbox) [reply torchvision/csrc/DeformConv.h:321]: I'll fix it on #2905

File: torchvision/csrc/DeformConv.h (hunk 2 above)
Comment (mthrok) [reply torchvision/csrc/DeformConv.h:81]: I encourage using `const` as much as possible. Having `const` might allow compilers to do some optimizations and it will prevent developer to accidentally overwrite the local variable.

File: torchvision/csrc/cpu/DeformConv_cpu.cpp (hunk 7 above)
Comment (ezyang) [reply torchvision/csrc/cpu/DeformConv_cpu.cpp:244]: Eh, it's pretty common in PyTorch codebase, if the kernel is written in such a way that it only works for contiguous inputs, you'll call contiguous first thing in the kernel. In fact, even in the linked code code you quoted is doing a contiguous call (there is just some extra gobbeldygook to reshape if there's batching involved).

Comment (ezyang) [reply torchvision/csrc/cpu/DeformConv_cpu.cpp:244]: The reason why it's wrong to call contiguous before the dispatcher call, is because you may enter the dispatcher directly via TorchScripted code. Of course you can call a TorchScripted function with non-contiguous inputs, so you had better have handling for the non-contiguous case somewhere!

Comment (fmassa) [reply torchvision/csrc/cpu/DeformConv_cpu.cpp:244]: Oh, I think there was a misunderstanding here. I was referring to the `&&`.

Comment (datumbox) [reply torchvision/csrc/cpu/DeformConv_cpu.cpp]: I removed the rvalue references.

File: torchvision/csrc/DeformConv.h (hunk 2 above)
Comment (datumbox) [reply torchvision/csrc/DeformConv.h:81]: @mthrok Defining constant primitives (final) is definitely an optimization for Java due to the way the JVM works, but are you sure it applies also in C++? My understanding is also that overusing it is considered an anti-pattern.

Comment (mthrok) [reply torchvision/csrc/DeformConv.h:81]: oh you are right, I was confused with JVM. Quick googling suggests a lot of articles about the myth. I will look at them. Thanks.

Comment (datumbox) [reply torchvision/csrc/DeformConv.h:81]: All good man, thanks for looking into this.

**Comment by fmassa** [comment]
Thanks a lot Vasilis!

File: torchvision/csrc/DeformConv.h (hunk 6 above)
Comment (datumbox) [reply torchvision/csrc/DeformConv.h:321]: [Done](https://github.com/pytorch/vision/pull/2905/commits/c0ad23f863215f954d09d213356d93b0f28ceb67).
